import Utils from "./Utils";
export default class Sender {
  constructor() {
    this.OBJECT_TO_SEND = {
      data: [
        "task(4o8dwlba9xhj3f1)",
        0,
        "a nice guy",
        "ugly face, no color, bad hands",
        [],
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        20,
        "DPM++ 2M SDE",
        4,
        0,
        "original",
        1,
        1,
        7,
        1.5,
        0.75,
        null,
        768,
        512,
        1,
        "Just resize",
        "Whole picture",
        32,
        "Inpaint masked",
        "",
        "",
        "",
        [],
        false,
        [],
        "",
        "None",
        false,
        "",
        0.8,
        -1,
        false,
        -1,
        0,
        0,
        0,
        null,
        null,
        null,
        null,
        "* `CFG Scale` should be 2 or lower.",
        true,
        true,
        "",
        "",
        true,
        50,
        true,
        1,
        0,
        false,
        4,
        0.5,
        "Linear",
        "None",
        '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>',
        128,
        8,
        ["left", "right", "up", "down"],
        1,
        0.05,
        128,
        4,
        "fill",
        ["left", "right", "up", "down"],
        false,
        false,
        "positive",
        "comma",
        0,
        false,
        false,
        "",
        '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>',
        64,
        "None",
        2,
        "Seed",
        "",
        [],
        "Nothing",
        "",
        [],
        "Nothing",
        "",
        [],
        true,
        false,
        false,
        false,
        0,
        false,
        null,
        null,
        false,
        null,
        null,
        false,
        null,
        null,
        false,
        50,
        [
          {
            name: "/Users/gaelhugo/Documents/gitHub/stable-diffusion-webui/outputs/img2img-images/2023-10-24/00157-505339994.png",
            data: "http://0.0.0.0:7860/file=/Users/gaelhugo/Documents/gitHub/stable-diffusion-webui/outputs/img2img-images/2023-10-24/00157-505339994.png",
            is_file: true,
          },
          {
            name: "/var/folders/yr/j142m30d3nj2jbnh_62303580000gn/T/gradio/tmpkualiviz.png",
            data: "http://0.0.0.0:7860/file=/var/folders/yr/j142m30d3nj2jbnh_62303580000gn/T/gradio/tmpkualiviz.png",
            is_file: true,
          },
        ],
        '{"prompt": "a nice guy", "all_prompts": ["a nice guy"], "negative_prompt": "ugly face, no color, bad hands", "all_negative_prompts": ["ugly face, no color, bad hands"], "seed": 505339994, "all_seeds": [505339994], "subseed": 1895317864, "all_subseeds": [1895317864], "subseed_strength": 0, "width": 512, "height": 768, "sampler_name": "DPM++ SDE", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_name": "cardosAnime_v20", "sd_model_hash": "86bd0c547c", "sd_vae_name": null, "sd_vae_hash": null, "seed_resize_from_w": -1, "seed_resize_from_h": -1, "denoising_strength": 0.65, "extra_generation_params": {"ControlNet 0": "Module: canny, Model: t2iadapter_canny_sd15v2 [cecee02b], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Threshold A: 100, Threshold B: 200, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced"}, "index_of_first_image": 0, "infotexts": ["a nice guy\\nNegative prompt: ugly face, no color, bad hands\\nSteps: 20, Sampler: DPM++ SDE, CFG scale: 7, Seed: 505339994, Size: 512x768, Model hash: 86bd0c547c, Model: cardosAnime_v20, Denoising strength: 0.65, ControlNet 0: \\"Module: canny, Model: t2iadapter_canny_sd15v2 [cecee02b], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Threshold A: 100, Threshold B: 200, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced\\", Version: v1.6.0"], "styles": [], "job_timestamp": "20231024232048", "clip_skip": 1, "is_using_inpainting_conditioning": false}',
        "<p>a nice guy<br>\nNegative prompt: ugly face, no color, bad hands<br>\nSteps: 20, Sampler: DPM++ SDE, CFG scale: 7, Seed: 505339994, Size: 512x768, Model hash: 86bd0c547c, Model: cardosAnime_v20, Denoising strength: 0.65, ControlNet 0: &quot;Module: canny, Model: t2iadapter_canny_sd15v2 [cecee02b], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Threshold A: 100, Threshold B: 200, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced&quot;, Version: v1.6.0</p>",
        "<p class='comments'></p><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>22.8 sec.</span></p></div>",
      ],
      event_data: null,
      fn_index: 697,
      session_hash: "5fbh3kcpcqi",
    };
    //update the session_hash with the right value
  }

  async postData(imageData, width, height, prompt, ctx = null) {
    const b64Img = Utils.getImageUrlWithResize(imageData, width, height);

    this.OBJECT_TO_SEND.data[2] = prompt;
    this.OBJECT_TO_SEND.data[5] = b64Img;
    this.OBJECT_TO_SEND.data[23] = parseInt(512);
    this.OBJECT_TO_SEND.data[24] = parseInt(512);

    return fetch("http://0.0.0.0:7860/run/predict/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(this.OBJECT_TO_SEND),
    })
      .then((response) => response.json())
      .catch((error) => {
        console.error("Error:", error);
      });
  }
}
